# --- Configuración Visual Llamativa (Modo Neón) ---

# EJEMPLO DE CONFIGURACION


# Fuente: 'Courier New' es muy distinta a la original (estilo maquina de escribir)
ui.font.family=Courier New

# Colores Hexadecimales muy contrastados
# Fondo de la calculadora en Gris muy oscuro
ui.color.panel.bg=#1A1A1B

# Pantalla: Fondo Negro con texto Verde Neon (Estilo Matrix)
ui.color.display.bg=#000000
ui.color.display.text=#39FF14

# Botones Numericos: Fondo Blanco puro con texto negro
ui.color.number.bg=#FFFFFF

# Botones de Funcion: Cian/Azul Electrico para que resalten
ui.color.function.bg=#00FFFF
